### ISSUE TITLE
해커톤 추천장소 내용 추가

### ISSUE THREAD

**Issue by JunHyunJunHyun** [KMU-OSS-Laboratory/Hackathon-Manual#5]
페이스북 이노베이션 랩에서 개발자 커뮤니티 생태계의 활성화를 위해 커뮤니티 데이 프로그램을 운영합니다.

아래와 같은 사항들을 지원해주고 있어 좋은 정보가 될 듯 하여 이슈 날립니다.

  1. 페이스북 이노베이션 랩 공간 지원: 세미나, 코워킹, 미팅 공간 등(간단한 간식과 음료 제공)
  2. 페이스북 이노베이션 랩과의 협업: 밋업, 해커톤 등 이벤트 공동 기획
  3. 페이스북 내부 리소스 제공 기회: 페이스북 엔지니어 초청, 페이스북 행사 참여 등
  
링크 : bit.ly/커뮤니티데이참여신청

**Comment by minsuklee** [comment]
링크와 함께 반영했습니다. 다른 장소 링크들도 (공평하게^^) 나중에 추가해야 할 것 같습니다. 지금 bit.ly 링크는 서베이몽키 링크가 지속가능성이 있을지 약간 의문은 있습니다.
